project_id = "thcsixalwxttcibuahyl"

[functions.generate-forecast]
verify_jwt = false

[functions.ml-demand-forecast]
verify_jwt = false

[functions.ai-demand-forecast]
verify_jwt = false

[functions.pharmacy-forecast]
verify_jwt = false
